### ISSUE TITLE
Error when setting default value to something else than the first.

### ISSUE THREAD

**Issue by bob-pixeldeluxe** [percipioglobal/craft-colour-swatches#128]
So im using this field for background colors in a matrix.
As soon as i select a default value other than the first i get the following error on the /admin edit page.
<img width="944" alt="Screenshot 2024-04-29 at 15 14 40" src="https://github.com/craftpulse/craft-colour-swatches/assets/50947605/25ab83e9-d5a7-48cd-99a4-dc79a9bfe3e3">

plugin version: 4.4.0
craft cms version: 4.8.10

**Comment by HBunnick** [comment]
Same issue here:

plugin version: 5.0.0
craft cms version: 5.1.1

**Comment by mylesthedev** [comment]
Also having this issue on Craft 5

**Comment by DavidKabelitz** [comment]
Same here

**Comment by DavidKabelitz** [comment]
No reaction? @bob-pixeldeluxe

**Comment by bob-pixeldeluxe** [comment]
@DavidKabelitz Nope nothing yet.

**Comment by michtio** [comment]
Thank you for mentioning everyone, sorry for the radio silence, currently going through some major changes. We will pick this up next week!

**Comment by DavidKabelitz** [comment]
@michtio Any Update here? Cause it's a major problem

**Comment by ruudvdboom** [comment]
Changing line 144 of /src/fields/ColourSwatches.php fixes it:

```$default = array_values(array_filter($this->options, function($option) {return $option['default'] == 1;}));```

Versions:
        "craftcms/cms": "4.10.4",
        "craftpulse/craft-colour-swatches": "4.4.0",

**Comment by phillipsandoveracademy** [comment]
This is happening to us as well.

Versions:
"craftcms/cms": "4.10.4",
"craftpulse/craft-colour-swatches": "4.4.0"

**Comment by michtio** [comment]
@ruudvdboom @phillipsandoveracademy @bob-pixeldeluxe @DavidKabelitz @HBunnick 

please update Colour Swatches to the latest version. This issue has already been fixed in Version [4.5.2](https://github.com/craftpulse/craft-colour-swatches/commit/488d81c4290ecf538d9b62658e5fb0e78ea35ee5) released the beginning of April..

@mediabeastnz this issue has been Fixed as well at the beginning of April in Version 5.0.2

Please make sure the composer dependencies are up to date.

Closing this issue.

**Comment by DavidKabelitz** [comment]
@michtio sorry it was and still is not fixed for Craft 4. It just works for Craft 5. That what the people are complaining here about. We removed it nevertheless cause customers are not very happy with a broken CMS for month, we were running on the latest version of it. Thx

**Comment by michtio** [comment]
> @michtio sorry it was and still is not fixed for Craft 4. It just works for Craft 5. That what the people are complaining here about. We removed it nevertheless cause customers are not very happy with a broken CMS for month, we were running on the latest version of it. Thx

It is fixed for Craft 4, in version 4.5.2 - I see here everyone mentions 4.4.0.

I got to the depths of it, apparently the sync (when we release a package) towards the Craft Composer repo was broken, so everyone kept getting `4.4.0` as latest version. This is now resolved (or should be) as well.

As advice I can only give you, don't use the `craft update` command, but use composer directly as per https://nystudio107.com/blog/updating-craft-cms-without-headaches
